# Generated by Django 4.2.7 on 2025-09-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_customsupplier_inventoryitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="location",
            field=models.CharField(
                blank=True, help_text="Storage location (e.g., A1-01)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="max_stock_level",
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="min_stock_level",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
