# Generated by Django 4.2.7 on 2025-09-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_alter_branch_phone_alter_organization_phone"),
        ("inventory", "0005_alter_category_name_alter_manufacturer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="purchasetransaction",
            name="transaction_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="paymentrecord",
            unique_together={("organization", "payment_number")},
        ),
        migrations.AlterUniqueTogether(
            name="purchasetransaction",
            unique_together={("organization", "transaction_number")},
        ),
    ]
