# Generated by Django 4.2.7 on 2025-09-19 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_paymentrecord_payment_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_purchased", models.PositiveIntegerField()),
                ("unit", models.CharField(default="pieces", max_length=50)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("batch_number", models.CharField(max_length=50)),
                ("manufacturing_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_items",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "purchase_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.purchasetransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Item",
                "verbose_name_plural": "Purchase Items",
                "ordering": ["-created_at"],
            },
        ),
    ]
