# Generated by Django 4.2.7 on 2025-09-20 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_alter_branch_phone_alter_organization_phone"),
        ("inventory", "0007_purchaseitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("expected_delivery_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to Supplier"),
                            ("supplier_reviewing", "Supplier Reviewing"),
                            ("supplier_confirmed", "Supplier Confirmed"),
                            ("supplier_rejected", "Supplier Rejected"),
                            ("buyer_reviewing", "Buyer Reviewing Quote"),
                            ("buyer_confirmed", "Buyer Confirmed"),
                            ("buyer_cancelled", "Buyer Cancelled"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("released", "Released from Supplier Stock"),
                            ("imported", "Imported to Buyer Stock"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "advance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("advance_paid", models.BooleanField(default=False)),
                ("advance_payment_date", models.DateTimeField(blank=True, null=True)),
                ("shipping_method", models.CharField(blank=True, max_length=100)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("shipped_date", models.DateTimeField(blank=True, null=True)),
                ("delivered_date", models.DateTimeField(blank=True, null=True)),
                (
                    "released_date",
                    models.DateTimeField(
                        blank=True, help_text="When supplier released stock", null=True
                    ),
                ),
                (
                    "imported_date",
                    models.DateTimeField(
                        blank=True, help_text="When buyer imported to stock", null=True
                    ),
                ),
                (
                    "buyer_notes",
                    models.TextField(
                        blank=True, help_text="Initial order notes from buyer"
                    ),
                ),
                (
                    "supplier_notes",
                    models.TextField(blank=True, help_text="Supplier response notes"),
                ),
                (
                    "buyer_delivery_notes",
                    models.TextField(
                        blank=True, help_text="Buyer notes after reviewing quote"
                    ),
                ),
                (
                    "shipping_notes",
                    models.TextField(blank=True, help_text="Shipping instructions"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_orders_as_buyer",
                        to="organizations.branch",
                    ),
                ),
                (
                    "buyer_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_orders_as_buyer",
                        to="organizations.organization",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bulk_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Buyer user who imported the stock",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_bulk_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supplier user who released the stock",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_bulk_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_orders_as_supplier",
                        to="organizations.organization",
                    ),
                ),
                (
                    "supplier_user",
                    models.ForeignKey(
                        help_text="Supplier admin user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_orders_as_supplier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Order",
                "verbose_name_plural": "Bulk Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkOrderStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bulk_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="inventory.bulkorder",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Order Status Log",
                "verbose_name_plural": "Bulk Order Status Logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkOrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("advance", "Advance Payment"),
                            ("full", "Full Payment"),
                            ("partial", "Partial Payment"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("online", "Online Payment"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateTimeField()),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bulk_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="inventory.bulkorder",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Order Payment",
                "verbose_name_plural": "Bulk Order Payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="BulkOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_requested", models.PositiveIntegerField()),
                ("buyer_notes", models.TextField(blank=True)),
                ("quantity_confirmed", models.PositiveIntegerField(default=0)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price set by supplier",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "supplier_notes",
                    models.TextField(
                        blank=True, help_text="Supplier notes about this item"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("quantity_shipped", models.PositiveIntegerField(default=0)),
                ("quantity_delivered", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bulk_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.bulkorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_order_items",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Order Item",
                "verbose_name_plural": "Bulk Order Items",
                "unique_together": {("bulk_order", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="bulkorder",
            index=models.Index(
                fields=["buyer_organization", "status"],
                name="inventory_b_buyer_o_dc0a4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bulkorder",
            index=models.Index(
                fields=["supplier_organization", "status"],
                name="inventory_b_supplie_b61d94_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bulkorder",
            index=models.Index(
                fields=["order_date"], name="inventory_b_order_d_e5407d_idx"
            ),
        ),
    ]
