# Generated by Django 4.2.7 on 2025-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_bulkorder_bulkorderstatuslog_bulkorderpayment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkorder",
            name="buyer_reconfirm_notes",
            field=models.TextField(
                blank=True, help_text="Buyer notes during reconfirmation"
            ),
        ),
        migrations.AddField(
            model_name="bulkorder",
            name="can_modify_items",
            field=models.BooleanField(
                default=True, help_text="Whether buyer can still modify items"
            ),
        ),
        migrations.AddField(
            model_name="bulkorder",
            name="delivery_notes",
            field=models.TextField(blank=True, help_text="Final delivery notes"),
        ),
        migrations.AddField(
            model_name="bulkorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Payment Pending"),
                    ("partial", "Partial Payment"),
                    ("completed", "Payment Completed"),
                    ("overdue", "Payment Overdue"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bulkorder",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="bulkorder",
            name="supplier_locked",
            field=models.BooleanField(
                default=False, help_text="Supplier has locked their response"
            ),
        ),
        migrations.AddField(
            model_name="bulkorder",
            name="total_paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="bulkorderitem",
            name="buyer_reconfirm_notes",
            field=models.TextField(
                blank=True, help_text="Buyer notes during reconfirmation"
            ),
        ),
        migrations.AddField(
            model_name="bulkorderitem",
            name="is_cancelled",
            field=models.BooleanField(
                default=False, help_text="Item cancelled by buyer"
            ),
        ),
        migrations.AddField(
            model_name="bulkorderitem",
            name="quantity_final",
            field=models.PositiveIntegerField(
                default=0, help_text="Final quantity after buyer reconfirmation"
            ),
        ),
        migrations.AddField(
            model_name="bulkorderpayment",
            name="cash_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bulkorderpayment",
            name="credit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bulkorderpayment",
            name="installment_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="bulkorderpayment",
            name="is_final_payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bulkorderpayment",
            name="online_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bulkorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted to Supplier"),
                    ("supplier_reviewing", "Supplier Reviewing"),
                    ("supplier_confirmed", "Supplier Confirmed"),
                    ("supplier_rejected", "Supplier Rejected"),
                    ("buyer_reviewing", "Buyer Reviewing Quote"),
                    ("buyer_confirmed", "Buyer Confirmed"),
                    ("buyer_reconfirming", "Buyer Reconfirming Order"),
                    ("buyer_cancelled", "Buyer Cancelled"),
                    ("payment_pending", "Payment Pending"),
                    ("payment_partial", "Partial Payment Made"),
                    ("payment_completed", "Payment Completed"),
                    ("ready_to_ship", "Ready to Ship"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("released", "Released from Supplier Stock"),
                    ("imported", "Imported to Buyer Stock"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bulkorderpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cheque", "Cheque"),
                    ("online", "Online Payment"),
                    ("credit", "Credit/Pay Later"),
                    ("mixed", "Mixed Payment"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="bulkorderpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("advance", "Advance Payment"),
                    ("installment", "Installment Payment"),
                    ("final", "Final Payment"),
                    ("full", "Full Payment"),
                    ("partial", "Partial Payment"),
                ],
                max_length=15,
            ),
        ),
    ]
