# Generated by Django 4.2.7 on 2025-09-20 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_alter_branch_phone_alter_organization_phone"),
        ("inventory", "0009_bulkorder_buyer_reconfirm_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("user", "User Supplier"),
                            ("custom", "Custom Supplier"),
                        ],
                        max_length=10,
                    ),
                ),
                ("supplier_name", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("stock_management", "Stock Management"),
                            ("bulk_order", "Bulk Order"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_id", models.CharField(max_length=50)),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "credit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("transaction_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "supplier_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["supplier_name", "organization"],
                        name="inventory_s_supplie_caf4d6_idx",
                    ),
                    models.Index(
                        fields=["supplier_user", "organization"],
                        name="inventory_s_supplie_731742_idx",
                    ),
                ],
                "unique_together": {("source_type", "reference_id")},
            },
        ),
    ]
