# Generated by Django 4.2.7 on 2025-10-14 06:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_bulkorder_advance_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkorderpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="on_time_delivery_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("95"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
