# Generated by Django 4.2.7 on 2026-01-28 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_billinghistory_organizationsubscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0012_alter_bulkorderpayment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rack name (e.g., Main Rack A)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('rows', models.PositiveIntegerField(help_text='Number of rows in the rack')),
                ('columns', models.PositiveIntegerField(help_text='Number of columns in the rack')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_racks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'ordering': ['name'],
                'unique_together': {('organization', 'branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RackSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text='Section identifier (e.g., A1, B2)', max_length=10)),
                ('row_number', models.PositiveIntegerField()),
                ('column_number', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Quantity of medicine in this section')),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(blank=True, help_text='Medicine currently stored in this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_sections', to='inventory.product')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='inventory.rack')),
            ],
            options={
                'verbose_name': 'Rack Section',
                'verbose_name_plural': 'Rack Sections',
                'ordering': ['rack', 'row_number', 'column_number'],
                'unique_together': {('rack', 'section_name')},
            },
        ),
        migrations.CreateModel(
            name='RackSectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_assigned', models.PositiveIntegerField()),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_assignments', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_assignments', to='inventory.product')),
                ('rack_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.racksection')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_rack_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rack Section Assignment',
                'verbose_name_plural': 'Rack Section Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
