# Generated by Django 5.2.6 on 2025-09-14 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+977-1-234567' or '9801234567' (10 digits for local Nepali numbers).", regex='^(?:\\+977[-]?\\d{1,2}[-]?\\d{6,8}|\\d{10})$')]),
        ),
    ]
