# Generated by Django 5.2.6 on 2025-09-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_text_password',
            field=models.CharField(blank=True, help_text='Plain text password for display purposes (not for authentication)', max_length=128),
        ),
    ]
