# Generated by Django 4.2.7 on 2025-09-19 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientvisit",
            name="attended_by",
        ),
        migrations.RemoveField(
            model_name="patientvisit",
            name="items_purchased",
        ),
        migrations.RemoveField(
            model_name="patientvisit",
            name="purpose",
        ),
        migrations.RemoveField(
            model_name="patientvisit",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_type",
            field=models.CharField(
                choices=[
                    ("outpatient", "Outpatient"),
                    ("inpatient", "Inpatient"),
                    ("emergency", "Emergency"),
                    ("regular", "Regular"),
                ],
                default="outpatient",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="patientvisit",
            name="chief_complaint",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientvisit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_patient_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientvisit",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="patientvisit",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                default="scheduled",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="patientvisit",
            name="visit_type",
            field=models.CharField(
                choices=[
                    ("consultation", "Consultation"),
                    ("follow_up", "Follow-up"),
                    ("emergency", "Emergency"),
                    ("routine_check", "Routine Check"),
                ],
                max_length=20,
            ),
        ),
    ]
