# Generated by Django 4.2.7 on 2026-01-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patientvisit_attended_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='credit_allowed',
            field=models.BooleanField(default=False, help_text='Whether this patient is allowed to purchase on credit'),
        ),
        migrations.AddField(
            model_name='patient',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum credit limit for this patient', max_digits=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current outstanding credit balance', max_digits=10),
        ),
    ]
