# Generated by Django 4.2.7 on 2025-09-19 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_pos_prescriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
