# Generated by Django 4.2.7 on 2025-09-19 22:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_purchaseitem"),
        ("patients", "0002_remove_patientvisit_attended_by_and_more"),
        ("pos", "0002_alter_prescription_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="return",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="card_last_four",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="customer",
        ),
        migrations.AddField(
            model_name="return",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="returns",
                to="patients.patient",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="credit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="patient_age",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="patient_gender",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="patient_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sale",
            name="patient_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="sale",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="allocated_batches",
            field=models.JSONField(
                blank=True, default=list, help_text="Details of batch allocations"
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_items",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="sale_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("online", "Online"),
                    ("credit", "Credit"),
                    ("insurance", "Insurance"),
                    ("mixed", "Mixed Payment"),
                ],
                default="cash",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
