# Generated by Django 4.2.7 on 2025-09-19 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_alter_branch_phone_alter_organization_phone"),
        ("pos", "0003_remove_return_customer_remove_sale_card_last_four_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="POSSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(blank=True, max_length=200)),
                ("business_address", models.TextField(blank=True)),
                ("business_phone", models.CharField(blank=True, max_length=20)),
                ("business_email", models.EmailField(blank=True, max_length=254)),
                ("receipt_footer", models.TextField(blank=True)),
                (
                    "receipt_logo",
                    models.ImageField(blank=True, null=True, upload_to="pos/receipts/"),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("tax_inclusive", models.BooleanField(default=False)),
                ("payment_methods", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_settings",
                        to="organizations.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_settings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS Settings",
                "verbose_name_plural": "POS Settings",
                "unique_together": {("organization", "branch")},
            },
        ),
    ]
