# Generated by Django 5.2.6 on 2025-09-14 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('pharmacy_chain', 'Pharmacy Chain'), ('hospital_pharmacy', 'Hospital Pharmacy'), ('retail_pharmacy', 'Retail Pharmacy'), ('wholesale_pharmacy', 'Wholesale Pharmacy'), ('online_pharmacy', 'Online Pharmacy')], default='retail_pharmacy', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='pending', max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=13.0, help_text='Default tax rate for the organization', max_digits=5)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('subscription_plan', models.CharField(default='basic', max_length=50)),
                ('subscription_status', models.CharField(default='active', max_length=20)),
                ('subscription_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('expiry_alert_days', models.PositiveIntegerField(default=30)),
                ('auto_reorder', models.BooleanField(default=False)),
                ('reorder_point', models.PositiveIntegerField(default=20)),
                ('require_prescription', models.BooleanField(default=True)),
                ('allow_discounts', models.BooleanField(default=True)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('expiry_alerts', models.BooleanField(default=True)),
                ('enable_api_access', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=100)),
                ('webhook_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_organization_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Unique branch code', max_length=20, unique=True)),
                ('type', models.CharField(choices=[('main', 'Main Branch'), ('branch', 'Branch'), ('warehouse', 'Warehouse'), ('distribution', 'Distribution Center')], default='branch', max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='active', max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('monday_open', models.TimeField(default='09:00:00')),
                ('monday_close', models.TimeField(default='18:00:00')),
                ('tuesday_open', models.TimeField(default='09:00:00')),
                ('tuesday_close', models.TimeField(default='18:00:00')),
                ('wednesday_open', models.TimeField(default='09:00:00')),
                ('wednesday_close', models.TimeField(default='18:00:00')),
                ('thursday_open', models.TimeField(default='09:00:00')),
                ('thursday_close', models.TimeField(default='18:00:00')),
                ('friday_open', models.TimeField(default='09:00:00')),
                ('friday_close', models.TimeField(default='18:00:00')),
                ('saturday_open', models.TimeField(default='09:00:00')),
                ('saturday_close', models.TimeField(default='17:00:00')),
                ('sunday_open', models.TimeField(blank=True, null=True)),
                ('sunday_close', models.TimeField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
