# Generated by Django 4.2.7 on 2025-10-14 06:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_branch_phone_alter_organization_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=11,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("13"),
                help_text="Default tax rate for the organization",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="max_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
