# Generated by Django 4.2.7 on 2026-01-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_billinghistory_organizationsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='medical_system',
            field=models.CharField(choices=[('allopathic', 'Allopathic (Western Medicine)'), ('ayurvedic', 'Ayurvedic (Traditional Medicine)'), ('hybrid', 'Hybrid (Both)')], default='allopathic', max_length=20),
        ),
    ]
